# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\Evaluacion programacion\BECAS.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 613)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 501, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\../../../Downloads/descargar (6).jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, -10, 521, 611))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;")
        self.label_5.setText("")
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 30, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_7.setObjectName("label_7")
        self.bt_adduser = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_adduser.setGeometry(QtCore.QRect(60, 540, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_adduser.setFont(font)
        self.bt_adduser.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\../../../Downloads/guardar-el-archivo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_adduser.setIcon(icon)
        self.bt_adduser.setObjectName("bt_adduser")
        self.bt_adduser_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_adduser_2.setGeometry(QtCore.QRect(340, 540, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_adduser_2.setFont(font)
        self.bt_adduser_2.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\../../../Downloads/borrar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_adduser_2.setIcon(icon1)
        self.bt_adduser_2.setObjectName("bt_adduser_2")
        self.bt_salir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_salir.setGeometry(QtCore.QRect(430, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salir.setFont(font)
        self.bt_salir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_salir.setStyleSheet("QPushButton{\n"
"background-color:qlineargradient(spread:pad,x1:0,y1:0.505682, x2:1, y2:0.477 ,stop:0 rgba(72,61,139,219), stop:1 rgba(0,0,139,225));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\../programa/cerrar-sesion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_salir.setIcon(icon2)
        self.bt_salir.setIconSize(QtCore.QSize(22, 21))
        self.bt_salir.setObjectName("bt_salir")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 110, 431, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.password_5 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.password_5.setFont(font)
        self.password_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.password_5.setTabletTracking(False)
        self.password_5.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.password_5.setText("")
        self.password_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.password_5.setPlaceholderText("")
        self.password_5.setObjectName("password_5")
        self.gridLayout.addWidget(self.password_5, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.password_2 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.password_2.setFont(font)
        self.password_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.password_2.setTabletTracking(False)
        self.password_2.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.password_2.setText("")
        self.password_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.password_2.setPlaceholderText("")
        self.password_2.setObjectName("password_2")
        self.gridLayout.addWidget(self.password_2, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.password_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.password_3.setFont(font)
        self.password_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.password_3.setTabletTracking(False)
        self.password_3.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.password_3.setText("")
        self.password_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.password_3.setPlaceholderText("")
        self.password_3.setObjectName("password_3")
        self.gridLayout.addWidget(self.password_3, 2, 1, 1, 1)
        self.password = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.password.setFont(font)
        self.password.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.password.setTabletTracking(False)
        self.password.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.password.setText("")
        self.password.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.password.setPlaceholderText("")
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.password_4 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.password_4.setFont(font)
        self.password_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.password_4.setTabletTracking(False)
        self.password_4.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.password_4.setText("")
        self.password_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.password_4.setPlaceholderText("")
        self.password_4.setObjectName("password_4")
        self.gridLayout.addWidget(self.password_4, 3, 1, 1, 1)
        self.bt_adduser_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_adduser_3.setGeometry(QtCore.QRect(210, 450, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_adduser_3.setFont(font)
        self.bt_adduser_3.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\../../../Downloads/imagen.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_adduser_3.setIcon(icon3)
        self.bt_adduser_3.setObjectName("bt_adduser_3")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 420, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.bt_adduser_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_adduser_4.setGeometry(QtCore.QRect(200, 540, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_adduser_4.setFont(font)
        self.bt_adduser_4.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\../../../Downloads/volver (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_adduser_4.setIcon(icon4)
        self.bt_adduser_4.setObjectName("bt_adduser_4")
        self.buscardatos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buscardatos.setGeometry(QtCore.QRect(50, 450, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.buscardatos.setFont(font)
        self.buscardatos.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\../../../Downloads/buscar (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buscardatos.setIcon(icon5)
        self.buscardatos.setObjectName("buscardatos")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "PROGRAMA DE BECAS"))
        self.bt_adduser.setText(_translate("MainWindow", "GUARDAR"))
        self.bt_adduser_2.setText(_translate("MainWindow", "LIMPIAR"))
        self.bt_salir.setText(_translate("MainWindow", "Salir"))
        self.label_12.setText(_translate("MainWindow", "PROMEDIO"))
        self.label_9.setText(_translate("MainWindow", "NOTA 1"))
        self.label_10.setText(_translate("MainWindow", "NOTA 2"))
        self.label_8.setText(_translate("MainWindow", "ALUMNO"))
        self.label_11.setText(_translate("MainWindow", "NOTA 3"))
        self.bt_adduser_3.setText(_translate("MainWindow", "IMPORTAR FOTO"))
        self.label_2.setText(_translate("MainWindow", "FOTO"))
        self.bt_adduser_4.setText(_translate("MainWindow", "VOLVER"))
        self.buscardatos.setText(_translate("MainWindow", "BUSCAR DATOS"))
