# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\Evaluacion programacion\Busqueda.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 489)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 531, 461))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\descargar (7).jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 551, 481))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;")
        self.label_5.setText("")
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 20, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_7.setObjectName("label_7")
        self.Nombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Nombre.setGeometry(QtCore.QRect(30, 110, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Nombre.setFont(font)
        self.Nombre.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Nombre.setTabletTracking(False)
        self.Nombre.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border-radius:15px;\n"
"color:rgba(255,255,255,230);\n"
"border:0.5px solid white;")
        self.Nombre.setText("")
        self.Nombre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Nombre.setObjectName("Nombre")
        self.bt_busqueda = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_busqueda.setGeometry(QtCore.QRect(350, 110, 131, 41))
        self.bt_busqueda.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\buscar (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_busqueda.setIcon(icon)
        self.bt_busqueda.setObjectName("bt_busqueda")
        self.foto = QtWidgets.QLabel(parent=self.centralwidget)
        self.foto.setGeometry(QtCore.QRect(310, 210, 221, 201))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.foto.setFont(font)
        self.foto.setStyleSheet("color:rgba(255,255,255,210);\n"
"border-radius:50% ;\n"
"\n"
"")
        self.foto.setText("")
        self.foto.setPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\imagen.png"))
        self.foto.setScaledContents(True)
        self.foto.setObjectName("foto")
        self.bt_volver = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_volver.setGeometry(QtCore.QRect(340, 420, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_volver.setFont(font)
        self.bt_volver.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\volver (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_volver.setIcon(icon1)
        self.bt_volver.setObjectName("bt_volver")
        self.bt_salir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_salir.setGeometry(QtCore.QRect(440, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salir.setFont(font)
        self.bt_salir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_salir.setStyleSheet("QPushButton{\n"
"background-color:qlineargradient(spread:pad,x1:0,y1:0.505682, x2:1, y2:0.477 ,stop:0 rgba(72,61,139,219), stop:1 rgba(0,0,139,225));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\cerrar-sesion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_salir.setIcon(icon2)
        self.bt_salir.setIconSize(QtCore.QSize(22, 21))
        self.bt_salir.setObjectName("bt_salir")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 170, 121, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nota1 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota1.setFont(font)
        self.nota1.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota1.setText("")
        self.nota1.setObjectName("nota1")
        self.verticalLayout.addWidget(self.nota1)
        self.nota2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota2.setFont(font)
        self.nota2.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota2.setText("")
        self.nota2.setObjectName("nota2")
        self.verticalLayout.addWidget(self.nota2)
        self.nota3 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota3.setFont(font)
        self.nota3.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota3.setText("")
        self.nota3.setObjectName("nota3")
        self.verticalLayout.addWidget(self.nota3)
        self.promedio = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.promedio.setFont(font)
        self.promedio.setStyleSheet("color:rgba(255,255,255,210);")
        self.promedio.setText("")
        self.promedio.setObjectName("promedio")
        self.verticalLayout.addWidget(self.promedio)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 170, 93, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nota1_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota1_2.setFont(font)
        self.nota1_2.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota1_2.setObjectName("nota1_2")
        self.verticalLayout_2.addWidget(self.nota1_2)
        self.nota2_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota2_2.setFont(font)
        self.nota2_2.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota2_2.setObjectName("nota2_2")
        self.verticalLayout_2.addWidget(self.nota2_2)
        self.nota3_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota3_2.setFont(font)
        self.nota3_2.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota3_2.setObjectName("nota3_2")
        self.verticalLayout_2.addWidget(self.nota3_2)
        self.promedio_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.promedio_2.setFont(font)
        self.promedio_2.setStyleSheet("color:rgba(255,255,255,210);")
        self.promedio_2.setObjectName("promedio_2")
        self.verticalLayout_2.addWidget(self.promedio_2)
        self.bt_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_clear.setGeometry(QtCore.QRect(60, 420, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_clear.setFont(font)
        self.bt_clear.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\borrar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_clear.setIcon(icon3)
        self.bt_clear.setObjectName("bt_clear")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "BUSCAR DATOS"))
        self.Nombre.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.bt_busqueda.setText(_translate("MainWindow", "BUSCAR"))
        self.bt_volver.setText(_translate("MainWindow", "VOLVER"))
        self.bt_salir.setText(_translate("MainWindow", "Salir"))
        self.nota1_2.setText(_translate("MainWindow", "NOTA1:"))
        self.nota2_2.setText(_translate("MainWindow", "NOTA2:"))
        self.nota3_2.setText(_translate("MainWindow", "NOTA3:"))
        self.promedio_2.setText(_translate("MainWindow", "PROMEDIO:"))
        self.bt_clear.setText(_translate("MainWindow", "LIMPIAR"))
