# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\Evaluacion programacion\CRUD.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 517)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 601, 491))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\Found this and thought you guys might like it.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 621, 511))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;")
        self.label_2.setText("")
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 171, 491))
        self.label_3.setStyleSheet("border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\9c21a057-3aaa-476a-b54d-2aecf8eaeebd.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.bt_datos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_datos.setGeometry(QtCore.QRect(40, 100, 111, 41))
        self.bt_datos.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\nueva-base-de-datos.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_datos.setIcon(icon)
        self.bt_datos.setIconSize(QtCore.QSize(24, 20))
        self.bt_datos.setObjectName("bt_datos")
        self.bt_registrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_registrar.setGeometry(QtCore.QRect(40, 170, 111, 41))
        self.bt_registrar.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\agregar-usuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_registrar.setIcon(icon1)
        self.bt_registrar.setIconSize(QtCore.QSize(24, 20))
        self.bt_registrar.setObjectName("bt_registrar")
        self.bt_load = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_load.setGeometry(QtCore.QRect(40, 240, 111, 41))
        self.bt_load.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\actualizar-flecha (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_load.setIcon(icon2)
        self.bt_load.setIconSize(QtCore.QSize(20, 20))
        self.bt_load.setObjectName("bt_load")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(190, 50, 411, 421))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(12)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_database = QtWidgets.QWidget()
        self.page_database.setObjectName("page_database")
        self.label_4 = QtWidgets.QLabel(parent=self.page_database)
        self.label_4.setGeometry(QtCore.QRect(160, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tourney ExtraBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.bt_refrescar = QtWidgets.QPushButton(parent=self.page_database)
        self.bt_refrescar.setGeometry(QtCore.QRect(290, 370, 101, 31))
        self.bt_refrescar.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        self.bt_refrescar.setIcon(icon)
        self.bt_refrescar.setIconSize(QtCore.QSize(24, 20))
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.tabla_estudiantes = QtWidgets.QTableWidget(parent=self.page_database)
        self.tabla_estudiantes.setGeometry(QtCore.QRect(0, 50, 411, 271))
        self.tabla_estudiantes.setStyleSheet("QTableWidget{\n"
"background-color:rgba(255,255,255);\n"
"gridline-color:black;\n"
"color: rgb(0,0,0);\n"
"color: #000000;\n"
"}\n"
"QHeaderView::section{\n"
"background-color: #b059b1;\n"
"border: 1 px solid rgb(0,0,0);\n"
"font-size:13px;\n"
"}\n"
"")
        self.tabla_estudiantes.setObjectName("tabla_estudiantes")
        self.tabla_estudiantes.setColumnCount(6)
        self.tabla_estudiantes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_estudiantes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_estudiantes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_estudiantes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_estudiantes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_estudiantes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_estudiantes.setHorizontalHeaderItem(5, item)
        self.stackedWidget.addWidget(self.page_database)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.label_5 = QtWidgets.QLabel(parent=self.page_register)
        self.label_5.setGeometry(QtCore.QRect(110, 20, 191, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:white;")
        self.label_5.setObjectName("label_5")
        self.Img = QtWidgets.QLabel(parent=self.page_register)
        self.Img.setGeometry(QtCore.QRect(300, 350, 91, 61))
        self.Img.setText("")
        self.Img.setScaledContents(True)
        self.Img.setObjectName("Img")
        self.bt_foto = QtWidgets.QPushButton(parent=self.page_register)
        self.bt_foto.setGeometry(QtCore.QRect(30, 360, 111, 41))
        self.bt_foto.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\imagen.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_foto.setIcon(icon3)
        self.bt_foto.setIconSize(QtCore.QSize(24, 20))
        self.bt_foto.setObjectName("bt_foto")
        self.bt_guardar = QtWidgets.QPushButton(parent=self.page_register)
        self.bt_guardar.setGeometry(QtCore.QRect(170, 360, 111, 41))
        self.bt_guardar.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        self.bt_guardar.setIcon(icon)
        self.bt_guardar.setIconSize(QtCore.QSize(24, 20))
        self.bt_guardar.setObjectName("bt_guardar")
        self.widget = QtWidgets.QWidget(parent=self.page_register)
        self.widget.setGeometry(QtCore.QRect(20, 71, 71, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:white;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:white;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:white")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:white;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:white;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_18 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:white;")
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.widget1 = QtWidgets.QWidget(parent=self.page_register)
        self.widget1.setGeometry(QtCore.QRect(180, 60, 171, 301))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ln_id = QtWidgets.QLineEdit(parent=self.widget1)
        self.ln_id.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.ln_id.setObjectName("ln_id")
        self.verticalLayout_2.addWidget(self.ln_id)
        self.ln_nombre = QtWidgets.QLineEdit(parent=self.widget1)
        self.ln_nombre.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.ln_nombre.setObjectName("ln_nombre")
        self.verticalLayout_2.addWidget(self.ln_nombre)
        self.ln_cedula = QtWidgets.QLineEdit(parent=self.widget1)
        self.ln_cedula.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.ln_cedula.setObjectName("ln_cedula")
        self.verticalLayout_2.addWidget(self.ln_cedula)
        self.ln_genero = QtWidgets.QLineEdit(parent=self.widget1)
        self.ln_genero.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.ln_genero.setObjectName("ln_genero")
        self.verticalLayout_2.addWidget(self.ln_genero)
        self.ln_carrera = QtWidgets.QLineEdit(parent=self.widget1)
        self.ln_carrera.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.ln_carrera.setObjectName("ln_carrera")
        self.verticalLayout_2.addWidget(self.ln_carrera)
        self.ln_ciudad = QtWidgets.QLineEdit(parent=self.widget1)
        self.ln_ciudad.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.ln_ciudad.setObjectName("ln_ciudad")
        self.verticalLayout_2.addWidget(self.ln_ciudad)
        self.stackedWidget.addWidget(self.page_register)
        self.page_reload = QtWidgets.QWidget()
        self.page_reload.setObjectName("page_reload")
        self.label_12 = QtWidgets.QLabel(parent=self.page_reload)
        self.label_12.setGeometry(QtCore.QRect(130, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:white;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.page_reload)
        self.label_13.setGeometry(QtCore.QRect(20, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:white;")
        self.label_13.setObjectName("label_13")
        self.alumno = QtWidgets.QLineEdit(parent=self.page_reload)
        self.alumno.setGeometry(QtCore.QRect(90, 60, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.alumno.setFont(font)
        self.alumno.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.alumno.setTabletTracking(False)
        self.alumno.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.alumno.setText("")
        self.alumno.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.alumno.setPlaceholderText("")
        self.alumno.setObjectName("alumno")
        self.bt_buscar = QtWidgets.QPushButton(parent=self.page_reload)
        self.bt_buscar.setGeometry(QtCore.QRect(310, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bt_buscar.setFont(font)
        self.bt_buscar.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\buscar (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_buscar.setIcon(icon4)
        self.bt_buscar.setObjectName("bt_buscar")
        self.bt_img = QtWidgets.QPushButton(parent=self.page_reload)
        self.bt_img.setGeometry(QtCore.QRect(20, 350, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bt_img.setFont(font)
        self.bt_img.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        self.bt_img.setIcon(icon3)
        self.bt_img.setObjectName("bt_img")
        self.label_imagen = QtWidgets.QLabel(parent=self.page_reload)
        self.label_imagen.setGeometry(QtCore.QRect(310, 190, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_imagen.setFont(font)
        self.label_imagen.setText("")
        self.label_imagen.setScaledContents(True)
        self.label_imagen.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_imagen.setObjectName("label_imagen")
        self.bt_actualizar = QtWidgets.QPushButton(parent=self.page_reload)
        self.bt_actualizar.setGeometry(QtCore.QRect(220, 350, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bt_actualizar.setFont(font)
        self.bt_actualizar.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\guardar-el-archivo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_actualizar.setIcon(icon5)
        self.bt_actualizar.setObjectName("bt_actualizar")
        self.widget2 = QtWidgets.QWidget(parent=self.page_reload)
        self.widget2.setGeometry(QtCore.QRect(20, 141, 61, 191))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(parent=self.widget2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:white;")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(parent=self.widget2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:white;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(parent=self.widget2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:white;")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(parent=self.widget2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:white;")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(parent=self.widget2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:white;")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.widget3 = QtWidgets.QWidget(parent=self.page_reload)
        self.widget3.setGeometry(QtCore.QRect(90, 133, 211, 201))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ID = QtWidgets.QLineEdit(parent=self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.ID.setFont(font)
        self.ID.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.ID.setTabletTracking(False)
        self.ID.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.ID.setText("")
        self.ID.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ID.setPlaceholderText("")
        self.ID.setObjectName("ID")
        self.verticalLayout_6.addWidget(self.ID)
        self.Cedula = QtWidgets.QLineEdit(parent=self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Cedula.setFont(font)
        self.Cedula.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Cedula.setTabletTracking(False)
        self.Cedula.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.Cedula.setText("")
        self.Cedula.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Cedula.setPlaceholderText("")
        self.Cedula.setObjectName("Cedula")
        self.verticalLayout_6.addWidget(self.Cedula)
        self.Genero = QtWidgets.QLineEdit(parent=self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Genero.setFont(font)
        self.Genero.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Genero.setTabletTracking(False)
        self.Genero.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.Genero.setText("")
        self.Genero.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Genero.setPlaceholderText("")
        self.Genero.setObjectName("Genero")
        self.verticalLayout_6.addWidget(self.Genero)
        self.Carrera = QtWidgets.QLineEdit(parent=self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Carrera.setFont(font)
        self.Carrera.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Carrera.setTabletTracking(False)
        self.Carrera.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.Carrera.setText("")
        self.Carrera.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Carrera.setPlaceholderText("")
        self.Carrera.setObjectName("Carrera")
        self.verticalLayout_6.addWidget(self.Carrera)
        self.Ciudad = QtWidgets.QLineEdit(parent=self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Ciudad.setFont(font)
        self.Ciudad.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Ciudad.setTabletTracking(False)
        self.Ciudad.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:0.5px solid rgba(153, 175, 255);\n"
"border-right:0.5px solid rgba(153, 175, 255);\n"
"\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.Ciudad.setText("")
        self.Ciudad.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Ciudad.setPlaceholderText("")
        self.Ciudad.setObjectName("Ciudad")
        self.verticalLayout_6.addWidget(self.Ciudad)
        self.stackedWidget.addWidget(self.page_reload)
        self.page_buscar = QtWidgets.QWidget()
        self.page_buscar.setObjectName("page_buscar")
        self.label_11 = QtWidgets.QLabel(parent=self.page_buscar)
        self.label_11.setGeometry(QtCore.QRect(150, 30, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:white;")
        self.label_11.setObjectName("label_11")
        self.Nombre = QtWidgets.QLineEdit(parent=self.page_buscar)
        self.Nombre.setGeometry(QtCore.QRect(20, 90, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Nombre.setFont(font)
        self.Nombre.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Nombre.setTabletTracking(False)
        self.Nombre.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border-radius:15px;\n"
"color:rgba(255,255,255,230);\n"
"border:0.5px solid white;")
        self.Nombre.setText("")
        self.Nombre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Nombre.setObjectName("Nombre")
        self.bt_busqueda = QtWidgets.QPushButton(parent=self.page_buscar)
        self.bt_busqueda.setGeometry(QtCore.QRect(290, 90, 111, 31))
        self.bt_busqueda.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        self.bt_busqueda.setIcon(icon4)
        self.bt_busqueda.setObjectName("bt_busqueda")
        self.foto = QtWidgets.QLabel(parent=self.page_buscar)
        self.foto.setGeometry(QtCore.QRect(280, 240, 111, 91))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.foto.setFont(font)
        self.foto.setStyleSheet("color:rgba(255,255,255,210);\n"
"border-radius:50% ;\n"
"\n"
"")
        self.foto.setText("")
        self.foto.setPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\imagen.png"))
        self.foto.setScaledContents(True)
        self.foto.setObjectName("foto")
        self.bt_delete = QtWidgets.QPushButton(parent=self.page_buscar)
        self.bt_delete.setGeometry(QtCore.QRect(260, 360, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_delete.setFont(font)
        self.bt_delete.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\borrar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_delete.setIcon(icon6)
        self.bt_delete.setObjectName("bt_delete")
        self.widget4 = QtWidgets.QWidget(parent=self.page_buscar)
        self.widget4.setGeometry(QtCore.QRect(10, 161, 61, 231))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nota1_2 = QtWidgets.QLabel(parent=self.widget4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota1_2.setFont(font)
        self.nota1_2.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota1_2.setObjectName("nota1_2")
        self.verticalLayout_3.addWidget(self.nota1_2)
        self.nota1_4 = QtWidgets.QLabel(parent=self.widget4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota1_4.setFont(font)
        self.nota1_4.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota1_4.setObjectName("nota1_4")
        self.verticalLayout_3.addWidget(self.nota1_4)
        self.nota1_6 = QtWidgets.QLabel(parent=self.widget4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota1_6.setFont(font)
        self.nota1_6.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota1_6.setObjectName("nota1_6")
        self.verticalLayout_3.addWidget(self.nota1_6)
        self.nota1_8 = QtWidgets.QLabel(parent=self.widget4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota1_8.setFont(font)
        self.nota1_8.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota1_8.setObjectName("nota1_8")
        self.verticalLayout_3.addWidget(self.nota1_8)
        self.nota1_9 = QtWidgets.QLabel(parent=self.widget4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nota1_9.setFont(font)
        self.nota1_9.setStyleSheet("color:rgba(255,255,255,210);")
        self.nota1_9.setObjectName("nota1_9")
        self.verticalLayout_3.addWidget(self.nota1_9)
        self.widget5 = QtWidgets.QWidget(parent=self.page_buscar)
        self.widget5.setGeometry(QtCore.QRect(90, 161, 171, 231))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.id = QtWidgets.QLabel(parent=self.widget5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.id.setFont(font)
        self.id.setStyleSheet("color:rgba(255,255,255,210);")
        self.id.setText("")
        self.id.setObjectName("id")
        self.verticalLayout_4.addWidget(self.id)
        self.cedula = QtWidgets.QLabel(parent=self.widget5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cedula.setFont(font)
        self.cedula.setStyleSheet("color:rgba(255,255,255,210);")
        self.cedula.setText("")
        self.cedula.setObjectName("cedula")
        self.verticalLayout_4.addWidget(self.cedula)
        self.genero = QtWidgets.QLabel(parent=self.widget5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.genero.setFont(font)
        self.genero.setStyleSheet("color:rgba(255,255,255,210);")
        self.genero.setText("")
        self.genero.setObjectName("genero")
        self.verticalLayout_4.addWidget(self.genero)
        self.carrera = QtWidgets.QLabel(parent=self.widget5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.carrera.setFont(font)
        self.carrera.setStyleSheet("color:rgba(255,255,255,210);")
        self.carrera.setText("")
        self.carrera.setObjectName("carrera")
        self.verticalLayout_4.addWidget(self.carrera)
        self.ciudad = QtWidgets.QLabel(parent=self.widget5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ciudad.setFont(font)
        self.ciudad.setStyleSheet("color:rgba(255,255,255,210);")
        self.ciudad.setText("")
        self.ciudad.setObjectName("ciudad")
        self.verticalLayout_4.addWidget(self.ciudad)
        self.stackedWidget.addWidget(self.page_buscar)
        self.page_city = QtWidgets.QWidget()
        self.page_city.setObjectName("page_city")
        self.tabla_ciudad = QtWidgets.QTableWidget(parent=self.page_city)
        self.tabla_ciudad.setGeometry(QtCore.QRect(0, 70, 411, 271))
        self.tabla_ciudad.setStyleSheet("QTableWidget{\n"
"background-color:rgba(255,255,255);\n"
"gridline-color:black;\n"
"color: rgb(0,0,0);\n"
"color: #000000;\n"
"}\n"
"QHeaderView::section{\n"
"background-color: #b059b1;\n"
"border: 1 px solid rgb(0,0,0);\n"
"font-size:13px;\n"
"}\n"
"")
        self.tabla_ciudad.setObjectName("tabla_ciudad")
        self.tabla_ciudad.setColumnCount(6)
        self.tabla_ciudad.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_ciudad.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_ciudad.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_ciudad.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_ciudad.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_ciudad.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_ciudad.setHorizontalHeaderItem(5, item)
        self.label_20 = QtWidgets.QLabel(parent=self.page_city)
        self.label_20.setGeometry(QtCore.QRect(90, 30, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:white;")
        self.label_20.setObjectName("label_20")
        self.City = QtWidgets.QLineEdit(parent=self.page_city)
        self.City.setGeometry(QtCore.QRect(10, 360, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.City.setFont(font)
        self.City.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.City.setTabletTracking(False)
        self.City.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border-radius:15px;\n"
"color:rgba(255,255,255,230);\n"
"border:0.5px solid white;")
        self.City.setText("")
        self.City.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.City.setObjectName("City")
        self.bt_buscarcity = QtWidgets.QPushButton(parent=self.page_city)
        self.bt_buscarcity.setGeometry(QtCore.QRect(270, 360, 111, 31))
        self.bt_buscarcity.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        self.bt_buscarcity.setIcon(icon4)
        self.bt_buscarcity.setObjectName("bt_buscarcity")
        self.stackedWidget.addWidget(self.page_city)
        self.bt_eliminar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_eliminar.setGeometry(QtCore.QRect(40, 310, 111, 41))
        self.bt_eliminar.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        self.bt_eliminar.setIcon(icon4)
        self.bt_eliminar.setIconSize(QtCore.QSize(24, 20))
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.bt_salir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_salir.setGeometry(QtCore.QRect(510, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salir.setFont(font)
        self.bt_salir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_salir.setStyleSheet("QPushButton{\n"
"background-color:qlineargradient(spread:pad,x1:0,y1:0.505682, x2:1, y2:0.477 ,stop:0 rgba(72,61,139,219), stop:1 rgba(0,0,139,225));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\cerrar-sesion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_salir.setIcon(icon7)
        self.bt_salir.setIconSize(QtCore.QSize(22, 21))
        self.bt_salir.setObjectName("bt_salir")
        self.bt_volver = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_volver.setGeometry(QtCore.QRect(200, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bt_volver.setFont(font)
        self.bt_volver.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_volver.setStyleSheet("QPushButton{\n"
"background-color:qlineargradient(spread:pad,x1:0,y1:0.505682, x2:1, y2:0.477 ,stop:0 rgba(72,61,139,219), stop:1 rgba(0,0,139,225));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\girar-a-la-izquierda.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_volver.setIcon(icon8)
        self.bt_volver.setIconSize(QtCore.QSize(22, 21))
        self.bt_volver.setObjectName("bt_volver")
        self.bt_city = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_city.setGeometry(QtCore.QRect(40, 370, 111, 41))
        self.bt_city.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(123, 104, 238,230), stop:1 rgba(85,98,112,226));\n"
"\n"
"\n"
"}")
        self.bt_city.setIcon(icon4)
        self.bt_city.setIconSize(QtCore.QSize(24, 20))
        self.bt_city.setObjectName("bt_city")
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.bt_datos.raise_()
        self.bt_registrar.raise_()
        self.bt_load.raise_()
        self.stackedWidget.raise_()
        self.bt_eliminar.raise_()
        self.bt_salir.raise_()
        self.bt_volver.raise_()
        self.bt_city.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_datos.setText(_translate("MainWindow", "Base de Datos"))
        self.bt_registrar.setText(_translate("MainWindow", "Registrar"))
        self.bt_load.setText(_translate("MainWindow", "Actualizar"))
        self.label_4.setText(_translate("MainWindow", "Estudiantes"))
        self.bt_refrescar.setText(_translate("MainWindow", "REFRESCAR"))
        item = self.tabla_estudiantes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabla_estudiantes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_estudiantes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CEDULA"))
        item = self.tabla_estudiantes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "GENERO"))
        item = self.tabla_estudiantes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CARRERA"))
        item = self.tabla_estudiantes.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CIUDAD"))
        self.label_5.setText(_translate("MainWindow", "REGISTRAR ALUMNO"))
        self.bt_foto.setText(_translate("MainWindow", "IMPORTAR FOTO"))
        self.bt_guardar.setText(_translate("MainWindow", "GUARDAR"))
        self.label_6.setText(_translate("MainWindow", "ID"))
        self.label_7.setText(_translate("MainWindow", "Nombre"))
        self.label_8.setText(_translate("MainWindow", "Cedula"))
        self.label_9.setText(_translate("MainWindow", "Genero"))
        self.label_10.setText(_translate("MainWindow", "Carrera"))
        self.label_18.setText(_translate("MainWindow", "Ciudad "))
        self.label_12.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.label_13.setText(_translate("MainWindow", "Nombre"))
        self.bt_buscar.setText(_translate("MainWindow", "BUSCAR"))
        self.bt_img.setText(_translate("MainWindow", "IMPORTAR FOTO"))
        self.bt_actualizar.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.label_14.setText(_translate("MainWindow", "ID"))
        self.label_15.setText(_translate("MainWindow", "Cedula"))
        self.label_16.setText(_translate("MainWindow", "Genero"))
        self.label_17.setText(_translate("MainWindow", "Carrera"))
        self.label_19.setText(_translate("MainWindow", "Ciudad"))
        self.label_11.setText(_translate("MainWindow", "BUSCAR"))
        self.Nombre.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.bt_busqueda.setText(_translate("MainWindow", "BUSCAR"))
        self.bt_delete.setText(_translate("MainWindow", "ELIMINAR"))
        self.nota1_2.setText(_translate("MainWindow", "ID :"))
        self.nota1_4.setText(_translate("MainWindow", "Cedula :"))
        self.nota1_6.setText(_translate("MainWindow", "Genero :"))
        self.nota1_8.setText(_translate("MainWindow", "Carrera :"))
        self.nota1_9.setText(_translate("MainWindow", "Ciudad:"))
        item = self.tabla_ciudad.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabla_ciudad.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_ciudad.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CEDULA"))
        item = self.tabla_ciudad.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "GENERO"))
        item = self.tabla_ciudad.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CARRERA"))
        item = self.tabla_ciudad.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CIUDAD"))
        self.label_20.setText(_translate("MainWindow", "BUSQUEDA POR CIUDAD"))
        self.City.setPlaceholderText(_translate("MainWindow", "Ciudad"))
        self.bt_buscarcity.setText(_translate("MainWindow", "BUSCAR"))
        self.bt_eliminar.setText(_translate("MainWindow", "Buscar y  Eliminar"))
        self.bt_salir.setText(_translate("MainWindow", "Salir"))
        self.bt_volver.setText(_translate("MainWindow", "Volver"))
        self.bt_city.setText(_translate("MainWindow", "Buscar por \n"
"  Ciudad"))
