# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\Evaluacion programacion\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(388, 484)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(370, 0))
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 341, 461))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;")
        self.label_2.setText("")
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(135, 95, 90, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_3.setObjectName("label_3")
        self.user = QtWidgets.QLineEdit(parent=self.widget)
        self.user.setGeometry(QtCore.QRect(80, 165, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user.setFont(font)
        self.user.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.user.setObjectName("user")
        self.password = QtWidgets.QLineEdit(parent=self.widget)
        self.password.setGeometry(QtCore.QRect(80, 230, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.loginboton = QtWidgets.QPushButton(parent=self.widget)
        self.loginboton.setGeometry(QtCore.QRect(30, 360, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginboton.setFont(font)
        self.loginboton.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"\n"
"border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(128, 0, 255,219), stop:1 rgba(85,98,112,226));\n"
"\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\../../../Downloads/entrar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.loginboton.setIcon(icon)
        self.loginboton.setIconSize(QtCore.QSize(19, 18))
        self.loginboton.setObjectName("loginboton")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(20, 10, 321, 441))
        self.label.setStyleSheet("\n"
"\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\descargar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.bt_salir = QtWidgets.QPushButton(parent=self.widget)
        self.bt_salir.setGeometry(QtCore.QRect(240, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salir.setFont(font)
        self.bt_salir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_salir.setStyleSheet("QPushButton{\n"
"background-color:qlineargradient(spread:pad,x1:0,y1:0.505682, x2:1, y2:0.477 ,stop:0 rgba(72,61,139,219), stop:1 rgba(0,0,139,225));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:15px;\n"
"background-color : rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(128, 0, 255,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\Evaluacion programacion\\cerrar-sesion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_salir.setIcon(icon1)
        self.bt_salir.setIconSize(QtCore.QSize(22, 21))
        self.bt_salir.setObjectName("bt_salir")
        self.passwordboton = QtWidgets.QPushButton(parent=self.widget)
        self.passwordboton.setGeometry(QtCore.QRect(50, 400, 251, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.passwordboton.setFont(font)
        self.passwordboton.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"\n"
"\n"
"background-color: rgb(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"color:rgba(123,104,238,210);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.passwordboton.setIcon(icon)
        self.passwordboton.setIconSize(QtCore.QSize(19, 18))
        self.passwordboton.setObjectName("passwordboton")
        self.registroboton = QtWidgets.QPushButton(parent=self.widget)
        self.registroboton.setGeometry(QtCore.QRect(180, 360, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.registroboton.setFont(font)
        self.registroboton.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,210);\n"
"\n"
"border-radius:20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"color:rgba(255,255,255,210);\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682 , x2:1 , y2:0.477,stop:0 rgba(128, 0, 255,219), stop:1 rgba(85,98,112,226));\n"
"\n"
"}\n"
"\n"
"")
        self.registroboton.setIcon(icon)
        self.registroboton.setIconSize(QtCore.QSize(19, 18))
        self.registroboton.setObjectName("registroboton")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.user.raise_()
        self.password.raise_()
        self.loginboton.raise_()
        self.bt_salir.raise_()
        self.passwordboton.raise_()
        self.registroboton.raise_()
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "LOGIN"))
        self.user.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.password.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.loginboton.setText(_translate("MainWindow", "Ingresar"))
        self.bt_salir.setText(_translate("MainWindow", "Salir"))
        self.passwordboton.setText(_translate("MainWindow", "¿Deseas cambiar su contraseña?"))
        self.registroboton.setText(_translate("MainWindow", "Crear usuario"))
